[project]
name = "fdi-pln2609"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "requests>=2.32.5",
    "ruff>=0.14.14",
    "uvicorn>=0.40.0",
]
